version: '3'

services:
  product-service:
    build:
      context: ./product-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@db/product_db

  user-service:
    build:
      context: ./user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@db/user_db

  order-service:
    build:
      context: ./order-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@db/order_db

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@db/payment_db
      - PAYSTACK_SECRET_KEY=your_paystack_secret_key

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
