services:
  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./services/product-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - microservices-network

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./services/user-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - microservices-network

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./services/order-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - microservices-network

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./services/payment-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3003:3003"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - microservices-network

  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

volumes:
  postgres_data:

networks:
  microservices-network:
    driver: bridge
